language: python

python: "3.7"

before install:
- mv travis_secrets.yaml secrets.yaml
- sudo apt-get install -y libudev-dev
- pip install getmac==0.8.1

install:
- pip3 install homeassistant

script:
- hass -c . --script check_config