language: python

python: "3.7"

before install:
  - touch fake_key.pem
  - mv travis_secrets.yaml secrets.yaml
#  - mv customize_sample.yaml customize.yaml
  - "sudo mkdir -p /ssl/ && sudo touch /ssl/fullchain.pem"
  - "sudo mkdir -p /ssl/ && sudo touch /ssl/privkey.pem"
  - "sudo mkdir -p /config/tmp"
  - sudo apt-get install -y libudev-dev
  - pip install getmac==0.8.1
install:
  - pip3 install homeassistant

script:
  - hass --version
  - "hass -c . --script check_config --info all | tee check.output"
  - '! less check.output | grep -q "Failed config"'
