language: python

python: "3.7"

os: linux

before_install:
#  - touch fake_key.pem
  - mv travis_secrets.yaml secrets.yaml
#  - mv customize_sample.yaml customize.yaml
#  - "sudo mkdir -p /ssl/ && sudo touch /ssl/fullchain.pem"
#  - "sudo mkdir -p /ssl/ && sudo touch /ssl/privkey.pem"
#  - "sudo mkdir -p /config/tmp"
  - sudo apt-get install -y libudev-dev
  - pip install getmac==0.8.1
#testing
  - git clone https://github.com/jomwells/ambilights.git
  - cd ambilights/
  - mv /custom_components ..
  - cd ..
  - git https://github.com/custom-components/breaking_changes.git
  - cd breaking_changes/
  - mv /custom_components ..

install:
  - pip3 install homeassistant


script:
  - hass --version
  - "hass -c . --script check_config --info all"
#  - "hass -c . --script check_config --info all | tee check.output"
#  - '! less check.output | grep -q "Failed config"'
