binary_sensor:
  - platform: mqtt
    name: Bathroom doors Sensor
    #state_topic: bathroomdoors/stat/STATUS
    state_topic: bathroomdoors/stat/RESULT
    payload_on: '{"POWER":"ON"}'
    payload_off: '{"POWER":"OFF"}'
    value_template: ''

  - platform: mqtt
    name: Bathroom doors  Sensor Battery
    state_topic: bathroomdoors/stat/BATT
    value_template: ''
