binary_sensor:
  - platform: mqtt
    name: Water Leak Celar Sensor
    state_topic: celarwatersensor/stat/STATUS
    value_template: ''
    device_class: moisture
  - platform: mqtt
    name: Water Leak Celar Sensor Battery
    state_topic: celarwatersensor/stat/BATT
    value_template: ''
    device_class: battery
    

